### ISSUE TITLE
ActiveSupport::Concern instead of Schizo::Role?

### ISSUE THREAD

**Issue by andriytyurnikov** [cjbottaro/schizo#11]
Do you see any drawbacks of using ActiveSupport::Concern instead of Schizo::Role?

**Comment by cjbottaro** [comment]
ActiveSupport is a pretty big dependency, that's all.  Maybe we could make it such that we could use _either_ ActiveSupport::Concern or Schizo::Role without making a hard dependency on ActiveSupport.
