### ISSUE TITLE
Facades are not DCI

### ISSUE THREAD

**Issue by ciscoheat** [cjbottaro/schizo#13]
Hello, sorry if this seems like bashing on your work, but for people coming here looking for information about DCI, it needs to be said.

In the documentation, you talk about not going against core concepts in DCI, but unfortunately Facades itself are breaking the core concept of not violating object identity. It can lead to very subtle bugs when the Role methods aren't attached directly to the object playing the Role.

Of course the library may be useful for you in other situations, but currently it's not DCI.

**Comment by cjbottaro** [comment]
I was unaware that object identity was a core concept to DCI.  If that's the case, then I don't think true DCI can be achieved in Ruby (specifically thinking about the ActiveRecord problem).  If you disagree, please share; I've been banging my head against this problem for a while now.

Also, does true DCI really matter?  A lot of design patterns that have been translated over to Ruby have been altered or simply don't even apply in the same manner because of Ruby's dynamic nature.

The documentation does have examples regarding some of the subtle bugs you're talking about (how #kind_of?, #instance_of? and #class works), but that was my best guess at what the library should do.  Should it go even further and modify #eql? and #hash so case statements work and the facades quack even more like the original objects?  Or should they not quack at all?

**Comment by ciscoheat** [comment]
The object identity requirement is a problem in most languages, but the ones that can do AST rewriting can enable true DCI. Maroon is a ruby gem written by one of the most knowledgeable DCI guys, doing that: https://github.com/runefs/maroon

I think true DCI is important for those who wants to achieve that. :) Having a solution that fails on the things you mention (I think object_id is another problem) works maybe 98-99% of the time, but is 98-99% working software ok? So from a DCI standpoint, quacking is not a viable solution unless you achieve true delegation. This post talks about that: http://saturnflyer.com/blog/jim/2012/07/06/the-gang-of-four-is-wrong-and-you-dont-understand-delegation/

**Comment by andriytyurnikov** [comment]
@ciscoheat Important thing here is ability to use DSLs that are based on class methods, right now we don't see that functionality in maroon or refinements or whenever else.
Please don't think that we too attached to facades, but so far this is the best solution we have for that kind of problem.

**Comment by ciscoheat** [comment]
If you want to call something DCI, it's just as important to adhere to its requirements. Again I don't want to bash on your library, I just want to inform you about an important requirement, and hopefully avoid confusion for beginners when they search for DCI and find something that looks like it but misses one vital point.

**Comment by andriytyurnikov** [comment]
@ciscoheat if you know where DCI is defined clearly - it could help (but I doubt you'll find such a thing).
Look, nobody is offended in any way, but more pragmatic comments would be much more constructive.
From pragmatic standpoint DCI is just three letters, until strictly defined AND implemented.
Maroon ignores DSLs based on class methods, which is like 90% of toolbox - not good enough for some of us.
Maybe we'll look at AST rewrite, if you have something interesting to tell about it - go on, maybe we'll implement per-method-invocation-facade with facade-state-transfer-on-method-invocation, maybe something else.

**Comment by ciscoheat** [comment]
This comment from Trygve (The DCI author) is quite clear: https://groups.google.com/d/msg/object-composition/MBvBMZzjW_M/up5XCKj59skJ

This one from Cope is informative (about halfway down) : https://groups.google.com/d/msg/object-composition/Vk0bqb6JFX0/siBjJxPAIPIJ

If you want it more strict, I recommend that you check out the execution model and see if you can find anything that goes against the object identity requirement. If you do, please let me or the DCI list know so we can improve it: http://folk.uio.no/trygver/2012/DCIExecutionModel-2.1.pdf

The AST rewrite is quite simple, here's an example how it can be done: https://groups.google.com/d/msg/object-composition/MBvBMZzjW_M/4i3kp66EDnQJ

**Comment by andriytyurnikov** [comment]
@ciscoheat Thanks, DCI Execution model looks very relevant. But I don't see identity problem highlighted there.
AST rewrite link is not about ruby, so I don't get it, sorry.
I'll ignore single messages on object composition so far: signal versus noise ratio is not good, and context kinda blured, also it has lot of opinions. 
Still I had my share of identity-related issues with facades, and trust me - everyone is open to suggestion here.
But still, I wish to explore ways to make facades 'invisible', while using them. Will lookup more about AST rewriting - sounds like powerful spell :) Feel free to share relevant stuff about it.

**Comment by ciscoheat** [comment]
The identity problem isn't highlighted in the article, but that doesn't mean the model isn't considering it. In section 3.3 there is relevant stuff about execution context.

The AST example given by Cope was in pseudocode, and gives a quite clear example how method rewriting is handled in most DCI implementations, to avoid any wrapper issues. I recommend studying it, and if you need ruby examples, look at maroon which is using the same idea.

About messages on the list: Maybe you don't understand I'm quoting the authors of DCI. What they say about their invention is not a matter of opinion. Since they put it in words and are still insisting on it, wrappers, facades, forwarding and other things related to object schizophrenia is not DCI, period.

AST rewrites sure are useful! The best experience I had with AST rewriting is the language Haxe, which has an incredibly easy and useful macro functionality for that. So if you want to catch on to the concept quickly, check it out: http://haxe.org/manual/macros

**Comment by andriytyurnikov** [comment]
The identity problem isn't highlighted in the article, which makes mentioning this article irrelevant in context of the discussion. 

You see @ciscoheat , my dad had career in electromechanical engineering, and if he will know that I make my decisions not based on facts and definitions, but on vague words and opinions of some dutch guy - he will ask me to change my family name.

So this guys highlighted importance of object equality/identity and comparison - that is cool, we'll try to address those issues. We think about automaticaly copying state from wrapper to original object, and this will be an answer to self schizophrenia - this is how we do decision-making and experiment. 

Discussing with facts points and definition - works. Mentioning Cope - doesn't.

"Authors of DCI told me that wrappers, facades, forwarding are bad. Period" -  such style will lead you nowhere dude, don't talk to me like that, please.

**Comment by ciscoheat** [comment]
Read section 3.3 and you will hopefully see the relevance, even though it's not written in 30pt bold text.

"We think about automaticaly copying state from wrapper to original object, and this will be an answer to self schizophrenia" - This shows your ignorance in the matter. What you are doing is not DCI. That is my whole and only point. I hope you can be humble enough to at least acknowledge that.

"Discussing with facts points and definition - works. Mentioning Cope - doesn't." - This is as dumb as thinking Steve Jobs didn't direct the iPad design. The definition is in his and Trygves quotes and isn't vague, if you need to see it in another location I suggest you write to them and ask for it.

**Comment by andriytyurnikov** [comment]
Dear @ciscoheat, thank you very much, for telling me how arrogant, ignorant and dumb I am, without addressing subject of discussion. 
You are blocked now, so don't bother yourself answering.
Now, please, go fuck yourself, thank you.

**Comment by ciscoheat** [comment]
You have some issues my friend, I hope you can sort them out.
