### ISSUE TITLE
Support for Namespaced Modules/Roles

### ISSUE THREAD

**Issue by lancecarlson** [cjbottaro/schizo#3]
Say you wanted to have:

``` ruby
module User do
  include Schizo::Data
end

module MyNS::AuthenticatingUser do
  extend Schizo::Role
end

user = User.new
user.as(MyNS::AuthenticatingUser) 
```

gives: NameError: wrong constant name MyNS::AuthenticatingUser

I understand that this may be funky because of the implementation with facades but maybe u have some good ideas? :)

**Comment by cjbottaro** [comment]
That looks like a legitimate bug with Schizo.  Will try to get to it this week.

**Comment by lancecarlson** [comment]
You are the best! :)

**Comment by cjbottaro** [comment]
Hey, I committed and pushed the fix.  I added a spec for it, but can you clone the repo, build the gem and test it before I release to RubyGems?

**Comment by lancecarlson** [comment]
Works like a charm! Will be using in production next week :)

BTW, I only tested one layer of namespacing. My requirements didn't call for any deeper levels of namespacing. :)

**Comment by lancecarlson** [comment]
Thanks!!
