### ISSUE TITLE
Feature: possibly as method inside of role module?

### ISSUE THREAD

**Issue by lancecarlson** [cjbottaro/schizo#4]
``` ruby
module Flying
end

module QuackingDuck
  extend Schizo::Role

  as(Flying)  # or maybe depends(Flying) or depends_on(Flying) ?

  ### methods that depend on Flying ###
end
```

I'm not sure if this is _smart_ as each behavior shouldn't rely on other behaviors but sometimes it seems like it is impossible (or that I'm going to have to be redundant with my code... OR I have to specify as more than once every single time OR that I will have to bring all of those methods into one behavior, but that sucks because you're pulling in unwanted behavior in other use cases)

What do you think?

**Comment by cjbottaro** [comment]
Schizo supports the idea of multiple roles like so:

``` ruby
module Flier
  extend Schizo::Role
  def fly; end
end

module Quacker
  extend Schizo::Role
  def quack; end
end

something = Something.new
something.as(Flier) do |flier|
  flier.as(Quacker) do |flier_and_quacker|
    flier_and_quacker.fly
    flier_and_quaker.quack
  end
end
```

That functionality exists, but is not well tested at all.

Also, as you say... I'm not sure it's _smart_ or _right_ to nest roles like that.  I'm very inexperienced with DCI.  Maybe if we find ourselves nesting roles, then we're "doing it wrong"?  I'm not sure.

**Comment by lancecarlson** [comment]
You can also include the other behaviors I guess too.. For example:

``` ruby
module Flier
  extend Schizo::Role
  def fly; end
end

module Quacker
  extend Schizo::Role
  include Flier
  def quack; end
end
```

There are cases where you would want behaviors to couple to each other. I think this API is OK :)

**Comment by lancecarlson** [comment]
Maybe this should be closed? :)
